title: PantileSoft
description: "Pstxy: Outlook .pst and .ost file reader"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - example_std.md
  - changelog.md
  - BingSiteAuth.xml
